### ISSUE TITLE
Uncaught TypeError: Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by RobTrew** [FoldingText/foldingtext-for-atom#14]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [foldingtext-for-atom](https://github.com/FoldingText/foldingtext-for-atom) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'node' of undefined

```
At /Users/robintrew/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor-element.coffee:486

TypeError: Cannot read property 'node' of undefined
  at ft-outline-editor.module.exports.OutlineEditorElement.focus (/Users/robintrew/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor-element.coffee:486:44)
  at OutlineEditor.module.exports.OutlineEditor.focus (/Users/robintrew/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor.coffee:849:28)
  at OutlineEditor.module.exports.OutlineEditor._updateSelectionIfNeeded (/Users/robintrew/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor.coffee:1204:8)
  at OutlineEditor.module.exports.OutlineEditor.moveSelectionRange (/Users/robintrew/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor.coffee:1079:6)
  at /Users/robintrew/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor.coffee:135:10
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at UndoManager.module.exports.UndoManager.undo (/Users/robintrew/.atom/packages/foldingtext-for-atom/lib/core/undo-manager.coffee:130:14)
  at OutlineEditor.module.exports.OutlineEditor.undo (/Users/robintrew/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor.coffee:1695:26)
  at ft-outline-editor.atom.commands.add.stopEventPropagationAndGroupUndo.core:undo (/Users/robintrew/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor-element.coffee:1014:27)
  at ft-outline-editor.newCommandListeners.(anonymous function) (/Users/robintrew/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor-element.coffee:836:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
     -3:34.7.0 core:cut (span.ft-body-text)
     -2:51.6.0 settings-view:open (span.ft-body-text)
     -1:49.2.0 core:paste (span.ft-body-text)
     -1:41.7.0 outline-editor:edit-link (ft-outline-editor#QJjpWOvR.beditor.textMode)
  2x -1:35 outline-editor:toggle-bold (ft-outline-editor#QJjpWOvR.beditor.textMode)
     -1:32.8.0 outline-editor:edit-link (ft-outline-editor#QJjpWOvR.beditor.textMode)
  3x -1:21.3.0 outline-editor:clear-formatting (ft-outline-editor#QJjpWOvR.beditor.textMode)
     -1:13.3.0 outline-editor:edit-link (ft-outline-editor#QJjpWOvR.beditor.textMode)
     -1:07.0 outline-editor:toggle-strikethrough (span.ft-body-text)
  2x -0:59.2.0 outline-editor:toggle-status-complete (span.ft-body-text)
  2x -0:55.5.0 outline-editor:toggle-underline (ft-outline-editor#QJjpWOvR.beditor.textMode)
     -0:41.5.0 outline-editor:edit-link (ft-outline-editor#QJjpWOvR.beditor.textMode)
     -0:11.6.0 core:cut (span.ft-body-text)
     -0:07.9.0 editor:newline (span.ft-body-text)
     -0:03.5.0 core:paste (span.ft-body-text)
     -0:01.3.0 core:undo (span.ft-body-text)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-language-xquery"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-light-syntax"
    ]
  },
  "foldingtext-for-atom": {
    "disableAnimation": true
  }
}
```
### Installed Packages

``` coffee
# User
foldingtext-for-atom, v0.1.1
foldingtext-markdown, v1.2.2
linter, v0.12.2
linter-coffeelint, v0.2.3
minimap, v4.8.0

# Dev
No dev packages
```

**Comment by jessegrosjean** [comment]
I'm going to mark this closed, assuming it was due to a number of bad imports that cropped up on 0.1.1, but are fixed (or at least a lot have been fixed) now in 0.1.4
