### ISSUE TITLE
Uncaught Error: Cannot find module './editor/OutlineEditor'

### ISSUE THREAD

**Issue by RobTrew** [FoldingText/foldingtext-for-atom#15]
![screen shot 2015-05-16 at 03 19 28](https://cloud.githubusercontent.com/assets/2305761/7664320/63c37930-fb7a-11e4-8f01-d71f33946457.png)

[Enter steps to reproduce below:]
1. Clicking on green `Active` tag in file shown (in line with data-type="CodeBlock")
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [foldingtext-for-atom](https://github.com/FoldingText/foldingtext-for-atom) package, v0.1.2
### Stack Trace

Uncaught Error: Cannot find module './editor/OutlineEditor'

```
At module.js:330

Error: Cannot find module './editor/OutlineEditor'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at FoldingTextService.Object.defineProperty.get [as OutlineEditor] (/Users/robintrew/.atom/packages/foldingtext-for-atom/lib/foldingtext-service.coffee:58:13)
  at HTMLAnchorElement.FoldingTextService.eventRegistery.listen.click (/Users/robintrew/.atom/packages/foldingtext-for-atom/lib/extensions/status/index.coffee:25:39)
  at EventRegistery.handleEvent (/Users/robintrew/.atom/packages/foldingtext-for-atom/lib/editor/event-registery.coffee:114:33)
  at HTMLBodyElement.<anonymous> (/Users/robintrew/.atom/packages/foldingtext-for-atom/lib/editor/event-registery.coffee:3:1)

```
### Commands

```
     -7:20.6.0 core:save (input.hidden-input)
     -6:26.2.0 core:copy (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-language-xquery"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-light-syntax"
    ]
  },
  "foldingtext-for-atom": {
    "disableAnimation": true
  }
}
```
### Installed Packages

``` coffee
# User
foldingtext-for-atom, v0.1.2
foldingtext-markdown, v1.2.2
linter, v0.12.2
linter-coffeelint, v0.2.3
minimap, v4.8.0

# Dev
No dev packages
```

**Comment by jessegrosjean** [comment]
Ha, fixed and deployed in 0.1.4 in my 10 minute check before bed! :)
