### ISSUE TITLE
Uncaught Error: Cannot find module './Constants'

### ISSUE THREAD

**Issue by obligated** [FoldingText/foldingtext-for-atom#24]
Hi,
Just installed atom to check out this lovely outliner. However, as soon as I hit 'New Outline', this error popped up.

Everything's latest, editor and folding text.
Thanks

``````
module.js:330
Error: Cannot find module './Constants'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/home/felix/.atom/packages/foldingtext-for-atom/lib/core/item-serializer.coffee:5:15)
    at Object.<anonymous> (/home/felix/.atom/packages/foldingtext-for-atom/lib/core/item-serializer.coffee:173:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)```
``````

**Comment by jessegrosjean** [comment]
Hi… thanks for trying it out. Are you using a case sensitive file system? I'm working on Mac OS X which is case insensitive and have just found a few places where I was importing using incorrect case.
