### ISSUE TITLE
Uncaught TypeError: Parameter 'url' must be a string, not undefined

### ISSUE THREAD

**Issue by adamprocter** [FoldingText/foldingtext-for-atom#52]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [foldingtext-for-atom](https://github.com/FoldingText/foldingtext-for-atom) package, v0.6.0
### Stack Trace

Uncaught TypeError: Parameter 'url' must be a string, not undefined

```
At url.js:90

TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:90:11)
    at urlParse (url.js:84:5)
    at Object.urlResolve [as resolve] (url.js:422:10)
    at HTMLAnchorElement.EventRegistery.listen.click (/Users/adamprocter/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor-element.coffee:1078:22)
    at EventRegistery.handleEvent (/Users/adamprocter/.atom/packages/foldingtext-for-atom/lib/editor/event-registery.coffee:161:35)
    at HTMLBodyElement.<anonymous> (/Users/adamprocter/.atom/packages/foldingtext-for-atom/lib/editor/event-registery.coffee:3:61)
```
### Commands

```
     -0:38.2.0 editor:indent (span.ft-body-text)
 10x -0:36.4.0 core:backspace (span.ft-body-text)
     -0:29.6.0 core:paste (span.ft-body-text)
     -0:26.5.0 core:move-down (input.)
     -0:24 editor:move-to-beginning-of-paragraph (input.)
  6x -0:21.1.0 core:backspace (span.ft-body-text)
     -0:17 editor:newline (span.ft-body-text)
     -0:12.7.0 core:backspace (span.ft-body-text)
  6x -0:11.7.0 core:move-left (span.ft-body-text)
     -0:10.6.0 core:backspace (span.ft-body-text)
     -0:09.9.0 core:move-left (span.ft-body-text)
     -0:09.3.0 core:move-down (span.ft-body-text)
     -0:08.5.0 core:backspace (span.ft-body-text)
     -0:07.8.0 editor:newline (span.ft-body-text)
 15x -0:07.4.0 core:backspace (span.ft-body-text)
     -0:03.5.0 core:paste (span.ft-body-text)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.8
color-picker, v2.0.4
foldingtext-for-atom, v0.6.0
foldingtext-markdown, v1.3.2
go-plus, v3.3.11
monokai, v0.14.0

# Dev
No dev packages
```

**Comment by jessegrosjean** [comment]
I think this is fixed in ac0452b3748b6533280c4bd548b0fbcc87eb5463
