### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bottom' of undefined

### ISSUE THREAD

**Issue by adamprocter** [FoldingText/foldingtext-for-atom#58]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [foldingtext-for-atom](https://github.com/FoldingText/foldingtext-for-atom) package, v0.6.2
### Stack Trace

Uncaught TypeError: Cannot read property 'bottom' of undefined

```
At /Users/adamprocter/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor-element.coffee:279

TypeError: Cannot read property 'bottom' of undefined
  at ft-outline-editor.module.exports.OutlineEditorElement.getClientRectForItemOffset (/Users/adamprocter/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor-element.coffee:292:25)
  at ft-outline-editor.module.exports.OutlineEditorElement.scrollToItemIfNeeded (/Users/adamprocter/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor-element.coffee:450:26)
  at OutlineEditor.module.exports.OutlineEditor.scrollToItemIfNeeded (/Users/adamprocter/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor.coffee:1892:27)
  at OutlineEditor.module.exports.OutlineEditor._updateSelectionIfNeeded (/Users/adamprocter/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor.coffee:1235:10)
  at OutlineEditor.module.exports.OutlineEditor.extendSelectionRange (/Users/adamprocter/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor.coffee:1155:6)
  at ft-outline-editor.module.exports.OutlineEditorElement.onMouseMove (/Users/adamprocter/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor-element.coffee:579:15)
  at later (/Users/adamprocter/.atom/packages/foldingtext-for-atom/lib/editor/raf-debounce.coffee:12:14)

```
### Commands

```
 15x -2:34.6.0 core:backspace (span.ft-body-text)
     -2:12 core:move-right (span.ft-body-text)
     -2:11.6.0 editor:newline (span.ft-body-text)
  2x -2:10.8.0 core:delete (span.ft-body-text)
  6x -2:08.8.0 core:backspace (span.ft-body-text)
     -1:50.7.0 editor:newline (span.ft-body-text)
     -1:47 core:backspace (span.ft-body-text)
     -1:42.2.0 outline-editor:toggle-bold (span.ft-body-text)
     -1:35.3.0 core:backspace (span.ft-body-text)
  2x -1:35.1.0 editor:newline (span.ft-body-text)
     -1:23 core:move-right (span.ft-body-text)
     -1:19.6.0 editor:newline (span.ft-body-text)
     -1:16.3.0 core:cut (span.ft-body-text)
     -1:14.8.0 editor:newline (span.ft-body-text)
     -1:14.7.0 editor:indent (span.ft-body-text)
     -1:14.3.0 core:paste (span.ft-body-text)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-html-preview, v0.1.8
foldingtext-for-atom, v0.6.2
foldingtext-markdown, v1.3.2
monokai, v0.14.0

# Dev
No dev packages
```

**Comment by CyrilPeponnet** [comment]
I have the same issue since I updated atom to 1.9.8

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.8
**System**: Mac OS X 10.11.6
**Thrown From**: [foldingtext-for-atom](https://github.com/FoldingText/foldingtext-for-atom) package, v0.9.2

### Stack Trace

Uncaught TypeError: Cannot read property 'bottom' of undefined

```
At /Users/neXus/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor-element.coffee:292

TypeError: Cannot read property 'bottom' of undefined
    at ft-outline-editor.module.exports.OutlineEditorElement.getClientRectForItemOffset (/Users/neXus/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor-element.coffee:292:25)
    at OutlineEditor.module.exports.OutlineEditor.getClientRectForItemOffset (/Users/neXus/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor.coffee:1903:27)
    at Selection.Object.defineProperty.get (/Users/neXus/.atom/packages/foldingtext-for-atom/lib/editor/selection.coffee:199:21)
    at ft-outline-editor.module.exports.OutlineEditorElement.focus (/Users/neXus/.atom/packages/foldingtext-for-atom/lib/editor/outline-editor-element.coffee:496:38)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:152:25)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:284:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:416:19)
    at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:381:21)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:566:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:639:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:690:17)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "go-debug",
      "symbol-gen",
      "platformio-ide",
      "platformio-ide-terminal",
      "tab-switcher"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".DS_Store",
      ".XcodeSupport",
      "Build",
      "*.xcodeproj",
      "Frameworks",
      "*.sublime-*",
      ".tm_properties",
      ".cappenvs",
      "*.cib",
      "webapp",
      ".coverage",
      "*.egg-info",
      "dist",
      "*.pyc",
      "dump.rdb",
      "debug.test",
      "debug"
    ],
    "packagesWithKeymapsDisabled": [
      "go-debug"
    ],
    "themes": [
      "atom-material-ui",
      "spacegray-black-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
aligner, v0.22.1 (active)
ansible-snippets, v0.2.0 (inactive)
atom-beautify, v0.29.10 (active)
atom-material-contrast-syntax, v0.2.0 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-ui, v1.3.3 (active)
atom-monokai, v0.10.4 (inactive)
auto-detect-indentation, v1.1.0 (active)
autocomplete-clang, v0.9.4 (active)
autocomplete-go, v1.1.1 (active)
autocomplete-python, v1.8.6 (active)
build, v0.65.0 (active)
builder-go, v1.0.1 (active)
busy, v0.6.0 (active)
color-picker, v2.2.2 (active)
environment, v1.2.0 (active)
expose, v0.12.1 (inactive)
file-icons, v1.7.18 (active)
foldingtext-for-atom, v0.9.2 (active)
g-code, v0.1.0 (inactive)
git-plus, v5.16.2 (inactive)
git-time-machine, v1.5.3 (inactive)
go-config, v1.2.3 (active)
go-debug, v0.1.19 (inactive)
go-get, v1.0.4 (active)
go-plus, v4.2.0 (active)
go-quick-import, v0.2.1-rc.0 (active)
godoc, v0.3.0 (active)
gofmt, v1.1.7 (active)
gometalinter-linter, v1.1.1 (active)
gorename, v1.0.3 (active)
highlight-selected, v0.11.2 (active)
increment-selection, v0.3.0 (inactive)
language-ansible, v0.1.11 (active)
language-docker, v1.1.7 (active)
language-ini, v1.16.0 (active)
language-objective-j, v0.2.0 (active)
language-puppet, v0.21.0 (active)
linter, v1.11.16 (active)
linter-ansible-linting, v1.2.0 (active)
linter-flake8, v1.13.2 (active)
linter-gcc, v0.6.15 (active)
linter-golinter, v1.2.0 (active)
linter-puppet, v1.0.0 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-writer, v2.5.1 (active)
minimap, v4.24.7 (active)
minimap-bookmarks, v0.3.1 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-pigments, v0.2.1 (active)
monokai-seti, v0.7.0 (inactive)
monokai-slate, v0.5.0 (inactive)
motepair2, v0.37.0 (active)
navigator-godef, v1.0.4 (active)
pigments, v0.31.2 (active)
platformio-ide, v1.4.0 (inactive)
platformio-ide-terminal, v2.1.1 (inactive)
project-manager, v2.9.7 (active)
python-tools, v0.6.8 (active)
rainbow-tabs, v2.2.1 (active)
scroll-searcher, v4.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
sort-lines, v0.14.0 (inactive)
spacegray-black-syntax, v0.1.4 (active)
spacegray-dark-neue-syntax, v1.3.0 (inactive)
spacegray-dark-neue-ui, v1.4.0 (inactive)
spacegray-dark-syntax, v0.2.0 (inactive)
spacegray-dark-ui, v0.12.0 (inactive)
spacegray-monokai-ui, v1.0.0 (inactive)
spacegray-peacock-ui, v1.0.0 (inactive)
spacegray-tomorrowdark-ui, v1.0.0 (inactive)
split-diff, v1.0.4 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
symbol-gen, v1.3.1 (inactive)
symbols-tree-view, v0.13.2 (active)
tab-switcher, v1.5.3 (inactive)
terminal-plus, v0.14.5 (active)
tester-go, v1.0.5 (active)
todo-show, v1.7.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by CyrilPeponnet** [comment]
Forget it... After a restart of the app the error is gone.
