### ISSUE TITLE
Failed to activate the foldingtext-for-atom package

### ISSUE THREAD

**Issue by bjmiller** [FoldingText/foldingtext-for-atom#87]
[Enter steps to reproduce:]

1. Start Atom, with foldingtext installed.

**Atom**: 1.17.0-beta0 x64
**Electron**: 1.3.14
**OS**: Mac OS X 10.11.6
**Thrown From**: [foldingtext-for-atom](https://github.com/FoldingText/foldingtext-for-atom) package 0.9.2

### Stack Trace

Failed to activate the foldingtext-for-atom package

```
At Cannot find module '/Applications/Atom Beta.app/Contents/Resources/app/src/panel-element'

Error: Cannot find module '/Applications/Atom Beta.app/Contents/Resources/app/src/panel-element'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app/src/module-cache.js:354:1)
    at Module.require (Applications/Atom%20Beta.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at /packages/foldingtext-for-atom/lib/extensions/ui/popovers.coffee:6:16)
    at /packages/foldingtext-for-atom/lib/extensions/ui/popovers.coffee:3:1)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom%20Beta.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at /packages/foldingtext-for-atom/lib/foldingtext.coffee:49:9
    at FoldingTextService.observeOutlineEditors (/packages/foldingtext-for-atom/lib/foldingtext-service.coffee:123:5)
    at Object.activate (/packages/foldingtext-for-atom/lib/foldingtext.coffee:47:43)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:253:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:642:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:623:1
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:618:1)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:600:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:831:1
```

### Commands

```
     -0:07.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.29.18 
atom-easy-jsdoc 4.12.1 
atom-ternjs 0.18.2 
atom-typescript 11.0.1 
autocomplete-paths 1.0.5 
blame 0.10.3 
brian1 0.0.0 
busy-signal 1.3.0 
change-case 0.6.5 
color-picker 2.2.5 
diagrams 0.26.4 
editorconfig 2.2.2 
file-icons 2.1.3 
foldingtext-for-atom 0.9.2 
font-preview 0.1.1 
hey-pane 0.2.2 
intentions 1.1.2 
language-babel 2.57.3 
language-docker 1.1.7 
language-groovy 0.6.0 
language-ini 1.19.0 
language-jade 0.7.2 
language-scala 1.1.8 
line-count 0.5.0 
linter 2.1.2 
linter-eslint 8.1.5 
linter-lesshint 3.0.1 
linter-sass-lint 1.7.4 
linter-ui-default 1.2.2 
local-history 4.0.1 
merge-conflicts 1.4.4 
minimap 4.27.1 
minimap-pigments 0.2.2 
pigments 0.39.1 
preview 0.17.0 
project-quick-open 0.5.0 
regex-railroad-diagram 0.16.0 
resize-indent 0.3.0 
shell-it 0.2.1 
single-click-open 0.2.2 
sloc 1.1.0 
smarter-tab-key 0.0.0 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.4 
tabs-to-spaces 1.0.3 
to-base64 0.5.2 
trailing-semicolon 1.1.0 
tree-view-copy-relative-path 1.1.0 
turbo-javascript 1.4.0 
valign 1.1.3 
```

**Comment by isidroAVILA** [comment]
Same issue here.

**Comment by jsthack** [comment]
Had the same issue, and now all my tags, statuses, and priorities won't show up, and the Keybindings don't work.

**Comment by MaloneQQ** [comment]
I had the same issue

**Comment by brownphotographic** [comment]
same issue

**Comment by brownphotographic** [comment]
Error: Cannot find module '/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/panel-element'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/robbrown/.atom/packages/foldingtext-for-atom/lib/extensions/ui/popovers.coffee:6:16)
    at Object.<anonymous> (/Users/robbrown/.atom/packages/foldingtext-for-atom/lib/extensions/ui/popovers.coffee:3:1)
    at Object.<anonymous> (/Users/robbrown/.atom/packages/foldingtext-for-atom/lib/extensions/ui/popovers.coffee:3:1)
    at Module.get_Module._compile (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /Users/robbrown/.atom/packages/foldingtext-for-atom/lib/foldingtext.coffee:49:9
    at FoldingTextService.observeOutlineEditors (/Users/robbrown/.atom/packages/foldingtext-for-atom/lib/foldingtext-service.coffee:123:5)
    at Object.activate (/Users/robbrown/.atom/packages/foldingtext-for-atom/lib/foldingtext.coffee:47:43)
    at Package.module.exports.Package.activateNow (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /private/var/folders/sn/xksvxxzx7jzgtzscpjp1_r1h0000gn/T/AppTranslocation/19469B91-70AB-4540-9DCC-5E0C4644ED54/d/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36

**Comment by brownphotographic** [comment]
argh! still seeing this, 80% of the times I launch. I have to quit several times and relaunch

**Comment by brownphotographic** [comment]
Now, every time I launch atom folding text does not load and I get this error. All fhtml files only open as raw HTML, with the exception of the last one I was editing, which loads as a folding text outline.

**Comment by andrei-1111** [comment]
I'm also seeing this bug when opening atom with `foldingtext-for-atom` installed.  

[Enter steps to reproduce:]

1. Open atom
2. Install `foldingtext-for-atom`

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [foldingtext-for-atom](https://github.com/FoldingText/foldingtext-for-atom) package 0.9.2


### Stack Trace

Failed to activate the foldingtext-for-atom package

```
At Cannot find module 'undefined/node_modules/first-mate/lib/grammar'

Error: Cannot find module 'undefined/node_modules/first-mate/lib/grammar'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:6:11)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:3:1)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:3:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:6:19)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:3:1)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:3:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.addStatusBarItemsIfReady (/packages/foldingtext-for-atom/lib/foldingtext.coffee:137:29)
    at Object.consumeStatusBarService (/packages/foldingtext-for-atom/lib/foldingtext.coffee:130:6)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:405:79)
```

### Commands

```
     -0:58.8.0 pane:show-item-1 (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
     -0:52.5.0 editor:newline (input.hidden-input)
     -0:51.8.0 core:move-up (input.hidden-input)
     -0:44.4.0 pane:show-item-2 (input.hidden-input)
     -0:42.3.0 pane:show-item-1 (div.package-detail.panels-item)
  3x -0:38.3.0 core:backspace (input.hidden-input)
     -0:36.5.0 pane:show-item-2 (input.hidden-input)
  2x -0:35.5.0 pane:show-item-1 (div.package-detail.panels-item)
     -0:33.7.0 pane:show-item-2 (input.hidden-input)
     -0:33 pane:show-item-1 (div.package-detail.panels-item)
     -0:30.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
  3x -0:18.4.0 core:move-left (input.hidden-input)
     -0:15.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
custom-title 1.0.1 
file-watcher 1.2.6 
foldingtext-for-atom 0.9.2 
intentions 1.1.2 
linter 2.1.4 
linter-flake8 2.3.0 
linter-pycodestyle 2.1.3 
linter-ui-default 1.7.1 
minimap 4.29.8 
monokai 0.24.0 
react 0.18.0 
script 3.18.1 
Sublime-Style-Column-Selection 1.7.4 
symbol-gen 1.3.1 
```

**Comment by kampiamodikuesto** [comment]
idem for me:( so this package is dead?

**Comment by phasmid42** [comment]
Same issue I met.

**Comment by iterating** [comment]
Cannot find module 'undefined/node_modules/first-mate/lib/grammar

**Comment by lproven** [comment]
I have the same. Duplicate report at issue #95.
