### ISSUE TITLE
Failed to Activate Foldingtext on Atom

### ISSUE THREAD

**Issue by phasmid42** [FoldingText/foldingtext-for-atom#95]
Please let me know what to do. Thanks!

Atom: 1.48.0 x64
Electron: 5.0.13
Chrome: 73.0.3683.121
Node: v12.0.0

The error report as follows:

`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.14.4
**Thrown From**: [foldingtext-for-atom](https://github.com/FoldingText/foldingtext-for-atom) package 0.9.2

### Stack Trace

Failed to activate the foldingtext-for-atom package

```
At Cannot find module 'undefined/node_modules/first-mate/lib/grammar'
Require stack:
- /Users/pallas/.atom/packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee
- /Users/pallas/.atom/packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee
- /Users/pallas/.atom/packages/foldingtext-for-atom/lib/foldingtext.coffee
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html

Error: Cannot find module 'undefined/node_modules/first-mate/lib/grammar'
Require stack:
- /Users/pallas/.atom/packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee
- /Users/pallas/.atom/packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee
- /Users/pallas/.atom/packages/foldingtext-for-atom/lib/foldingtext.coffee
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155487)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146819)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:6:11)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:3:1)
    at /packages/foldingtext-for-atom/lib/extensions/item-path-grammar.coffee:3:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147503)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146819)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:6:19)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:3:1)
    at /packages/foldingtext-for-atom/lib/extensions/search-status-bar-item.coffee:3:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147503)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146819)
    at Object.addStatusBarItemsIfReady (/packages/foldingtext-for-atom/lib/foldingtext.coffee:137:29)
    at Object.consumeStatusBarService (/packages/foldingtext-for-atom/lib/foldingtext.coffee:130:6)
    at Provider.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1060525)
    at ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3187638)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3195870)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3192625)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3191949
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3189559)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3191809
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3191752)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382948)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:926785
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:921391)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1063432)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1063638)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

### Commands

```
  2x -0:04.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
foldingtext-for-atom 0.9.2 
foldingtext-markdown 1.3.2 
```

`

**Comment by lproven** [comment]
I have the same problem. This is a duplicate of issue #87 though.
